#ifndef zikzak_inappWEBVIEW_PLUGIN_PLUGIN_SCRIPTS_UTIL_H_
#define zikzak_inappWEBVIEW_PLUGIN_PLUGIN_SCRIPTS_UTIL_H_

#include <string>

namespace zikzak_inappwebview_plugin
{
  const std::string VAR_PLACEHOLDER_VALUE = "$IN_APP_WEBVIEW_PLACEHOLDER_VALUE";
  const std::string VAR_PLACEHOLDER_MEMORY_ADDRESS_VALUE = "$IN_APP_WEBVIEW_PLACEHOLDER_MEMORY_ADDRESS_VALUE";
  const std::string VAR_FUNCTION_ARGUMENT_NAMES = "$IN_APP_WEBVIEW_FUNCTION_ARGUMENT_NAMES";
  const std::string VAR_FUNCTION_ARGUMENT_VALUES = "$IN_APP_WEBVIEW_FUNCTION_ARGUMENT_VALUES";
  const std::string VAR_FUNCTION_BODY = "$IN_APP_WEBVIEW_FUNCTION_BODY";
}

#endif //zikzak_inappWEBVIEW_PLUGIN_PLUGIN_SCRIPTS_UTIL_H_
